### ISSUE TITLE
Tool for defining and enforcing project folder structure?

### ISSUE THREAD

**Issue by jonathanmach** [jonathanmach/the-mastery-lab#8]
#### Brainstorming

```YAML
# Templates: can be created via cli:
#     $ gen --template=new_domain $name=blogposts
#     $ gen --template=new_domain $name=users
templates:
  new_domain:
    $name/:
      - api/:
        participant/:
          - schemas.py
          - controllers.py
          - errors.py
        admin/:
          - schemas.py
          - controllers.py
          - errors.py
        rpc/:
          - handlers.py
          - serializers.py
          - errors.py
      - dtos.py
      - exceptions.py
      - models.py
      - services.py
      - utils.py

#
# Project structure specification
#
src/:
  domains/: { many: "@domain_module" }
  core/:
    auth/: "*"
  tools/: "*"
  integrations/: "*"
  tests/: "*"

#
# Composables
#
composables:
  # accessed with trailing '@'
  domain_module:
    api/:
      participant/:
        - schemas.py
        - controllers.py
        - errors.py? # same as: { _required: false }
      admin/:
        - schemas.py
        - controllers.py
        - errors.py
      external_api?: "@external_api" # same as: { _composable: "external_api", _required: false }
    dtos.py: { _required: false }
    exceptions.py:
    models.py:
    services.py:
    utils.py: { _required: false }

  external_api:
    - v1/:
        - schemas.py
        - controllers.py
        - errors.py
    - auth.py
    - middlewares.py
```
